# ============================================================================
# Script de entrega: fechas reales de apertura desde directorio.fpt.com.mx
# ============================================================================
# Reemplaza las fechas tentativas (limite - 7 dias) por las fechas REALES que
# aparecen en https://directorio.fpt.com.mx/ para 46 de los 47 clubes ya
# marcados como abiertos. Gransur y Multiplaza Las Palmas quedan en 27-dic-2025
# (confirmado contigo). "Portal Queretaro, QRO" no aparece en el directorio,
# asi que se queda sin tocar -- el script lo reporta al final.
#
# El Refugio, Melt Polanco, Izazaga, Escobedo, Cuatro Caminos, Glorieta,
# Andamar y Tlatelolco NO se tocan porque no tienen contrato de franquicia
# cargado en el sistema todavia.
#
# Como usarlo:
#   1) Corre este script desde la raiz del repo (fpt-contratos) en PowerShell.
#   2) git add -A ; git commit -m "..." ; git push
#   3) Con la DATABASE_URL de produccion en un .env local dentro de backend/:
#        npm run fix:franquicias-fechas-directorio
#      Revisa en la consola cuantos se actualizaron (deberian ser 46) y la
#      lista de clubes que quedaron sin tocar al final.
#      Borra el .env al terminar.
# ============================================================================

function Write-FileFromBase64 {
    param(
        [string]$RelativePath,
        [string]$Base64Content
    )
    $fullPath = Join-Path (Get-Location) $RelativePath
    $dir = Split-Path $fullPath -Parent
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    $bytes = [System.Convert]::FromBase64String($Base64Content)
    [System.IO.File]::WriteAllBytes($fullPath, $bytes)
    Write-Host "Escrito: $RelativePath"
}

Write-Host "Agregando fechas reales de apertura (directorio.fpt.com.mx)..."

$b64 = @"
ewogICJuYW1lIjogImZwdC1jb250cmF0b3MtYmFja2VuZCIsCiAgInZlcnNpb24iOiAiMC4xLjAiLAogICJwcml2YXRlIjogdHJ1ZSwKICAiZGVzY3JpcHRp
b24iOiAiQmFja2VuZCBkZSBsYSBwbGF0YWZvcm1hIGRlIGdlc3Rpw7NuIGNvbnRyYWN0dWFsIChDTE0pIGRlIEZpdG5lc3MgUGFyYSBUb2RvcyAoRlBUKSIs
CiAgIm1haW4iOiAic3JjL3NlcnZlci5qcyIsCiAgInNjcmlwdHMiOiB7CiAgICAic3RhcnQiOiAibm9kZSBzcmMvc2VydmVyLmpzIiwKICAgICJkZXYiOiAi
bm9kZSAtLXdhdGNoIHNyYy9zZXJ2ZXIuanMiLAogICAgInNlZWQiOiAibm9kZSBwcmlzbWEvc2VlZC5qcyIsCiAgICAibWlncmF0ZTphcnJlbmRhbWllbnRv
cyI6ICJub2RlIHByaXNtYS9taWdyYXRlX2FycmVuZGFtaWVudG9zLmpzIiwKICAgICJtaWdyYXRlOmZyYW5xdWljaWEtYWxlcnRhcyI6ICJub2RlIHByaXNt
YS9taWdyYXRlX2ZyYW5xdWljaWFfYWxlcnRhcy5qcyIsCiAgICAiZml4OmZyYW5xdWljaWFzLWZpcm1hZG8iOiAibm9kZSBwcmlzbWEvbWFyY2FyX2ZyYW5x
dWljaWFzX2Zpcm1hZGFzLmpzIiwKICAgICJtaWdyYXRlOmZyYW5xdWljaWEtY2x1Yi1hYmllcnRvIjogIm5vZGUgcHJpc21hL21pZ3JhdGVfZnJhbnF1aWNp
YV9jbHViX2FiaWVydG8uanMiLAogICAgImZpeDpmcmFucXVpY2lhcy1jbHViLWFiaWVydG8iOiAibm9kZSBwcmlzbWEvbWFyY2FyX2NsdWJlc19ub19hYmll
cnRvcy5qcyIsCiAgICAiZml4OmZyYW5xdWljaWFzLWVuLWNvbnN0cnVjY2lvbiI6ICJub2RlIHByaXNtYS9tYXJjYXJfY2x1YmVzX2VuX2NvbnN0cnVjY2lv
bi5qcyIsCiAgICAibGlzdGFyOmZyYW5xdWljaWFzIjogIm5vZGUgcHJpc21hL2xpc3Rhcl9mcmFucXVpY2lhcy5qcyIsCiAgICAiZml4OmZyYW5xdWljaWFz
LWZlY2hhcy1mdXR1cmFzIjogIm5vZGUgcHJpc21hL2NvcnJlZ2lyX2ZlY2hhc19mdXR1cmFzLmpzIiwKICAgICJmaXg6ZnJhbnF1aWNpYXMtYXBlcnR1cmFz
LWNvbmZpcm1hZGFzIjogIm5vZGUgcHJpc21hL21hcmNhcl9hcGVydHVyYXNfY29uZmlybWFkYXMuanMiLAogICAgImZpeDpmcmFucXVpY2lhcy1mZWNoYXMt
ZGlyZWN0b3JpbyI6ICJub2RlIHByaXNtYS9tYXJjYXJfZmVjaGFzX3JlYWxlc19kaXJlY3RvcmlvLmpzIgogIH0sCiAgImRlcGVuZGVuY2llcyI6IHsKICAg
ICJiY3J5cHQiOiAiXjYuMC4wIiwKICAgICJjb3JzIjogIl4yLjguNSIsCiAgICAiZG9jeHRlbXBsYXRlciI6ICJeMy42OS4zIiwKICAgICJkb3RlbnYiOiAi
XjE2LjQuNSIsCiAgICAiZXhwcmVzcyI6ICJeNC4xOS4yIiwKICAgICJleHByZXNzLWFzeW5jLWVycm9ycyI6ICJeMy4xLjEiLAogICAgImpzb253ZWJ0b2tl
biI6ICJeOS4wLjIiLAogICAgIm11bHRlciI6ICJeMS40LjUtbHRzLjEiLAogICAgIm5vZGUtY3JvbiI6ICJeMy4wLjMiLAogICAgInBnIjogIl44LjEyLjAi
LAogICAgInBpenppcCI6ICJeMy4yLjAiCiAgfQp9Cg==
"@
Write-FileFromBase64 -RelativePath "backend/package.json" -Base64Content $b64

$b64 = @"
Ly8gQ29ycmVjY2lvbiBtYXNpdmE6IHJlZW1wbGF6YSBsYXMgZmVjaGFzIGRlIGFwZXJ0dXJhIFRFTlRBVElWQVMgKGZlY2hhX2xpbWl0ZV9hcGVydHVyYSAt
IDcKLy8gZGlhcywgYXNpZ25hZGFzIHBvciBtYXJjYXJfY2x1YmVzX25vX2FiaWVydG9zLmpzIGNvbW8gYXByb3hpbWFjaW9uIGRlIHBhcnRpZGEpIHBvciBs
YXMKLy8gZmVjaGFzIFJFQUxFUyBwdWJsaWNhZGFzIGVuIGh0dHBzOi8vZGlyZWN0b3Jpby5mcHQuY29tLm14LyAoZnVlbnRlIG9maWNpYWwgZGVsIGFyZWEg
ZGUKLy8gT3BlcmFjaW9uZXMsIGNvbiBmZWNoYSBkZSBhcGVydHVyYSByZWFsIHBvciBjbHViKS4KLy8KLy8gQ29uZmlybWFkbyBjb24gSmFpciAoMjAyNi0x
MC0wMyk6IEdyYW5zdXIgeSBNdWx0aXBsYXphIExhcyBQYWxtYXMgKEdSTykgYWJyaWVyb24gZWwKLy8gMjctZGljLTIwMjUgc2VndW4gZWwgZGlyZWN0b3Jp
byAobm8gMjktZGljLTIwMjYgY29tbyBzZSBoYWJpYSBkaWNobyBhbnRlcykuIFNlIHVzYSBsYQovLyBmZWNoYSBkZWwgZGlyZWN0b3JpbyBwYXJhIGFtYm9z
LgovLwovLyBDbHViZXMgZGVsIGRpcmVjdG9yaW8gbWFyY2Fkb3MgIlBvciBhYnJpciIgKEVsIFJlZnVnaW8sIE1lbHQgUG9sYW5jbywgSXphemFnYSwgRXNj
b2JlZG8pIE5PCi8vIGVzdGFuIGVuIGVzdGEgbGlzdGEgcG9ycXVlIG5vIGV4aXN0ZW4gdG9kYXZpYSBjb21vIGNvbnRyYXRvIGRlIGZyYW5xdWljaWEgZW4g
ZWwgc2lzdGVtYSAtLQovLyBuYWRhIHF1ZSBhY3R1YWxpemFyIGhhc3RhIHF1ZSBzZSBjcmVlIHN1IGNvbnRyYXRvLiBMbyBtaXNtbyBwYXJhIEdsb3JpZXRh
LCBBbmRhbWFyLAovLyBUbGF0ZWxvbGNvIHkgQ3VhdHJvIENhbWlub3MgKHRhbXBvY28gdGllbmVuIGNvbnRyYXRvIGNhcmdhZG8pLgovLwovLyBVbiBjbHVi
IGRlbCBzaXN0ZW1hLCAiUG9ydGFsIFF1ZXJldGFybywgUVJPIiwgbm8gYXBhcmVjZSBlbiBlbCBkaXJlY3RvcmlvIGVuIGFic29sdXRvLCBhc2kKLy8gcXVl
IG5vIHNlIHRvY2EgYXF1aSAoc2UgcXVlZGEgY29uIHN1IGZlY2hhIHRlbnRhdGl2YSBhbnRlcmlvciBoYXN0YSB0ZW5lciB1biBkYXRvIHJlYWwpLgovLwov
LyBFamVjdXRhciBjb246Ci8vICAgbm9kZSBwcmlzbWEvbWFyY2FyX2ZlY2hhc19yZWFsZXNfZGlyZWN0b3Jpby5qcwovLyBTZWd1cm8gZGUgY29ycmVyIG1h
cyBkZSB1bmEgdmV6IChzaWVtcHJlIHZ1ZWx2ZSBhIHBvbmVyIGxhIG1pc21hIGZlY2hhIHJlYWwpLgoKcmVxdWlyZSgnZG90ZW52JykuY29uZmlnKCk7CmNv
bnN0IHsgQ2xpZW50IH0gPSByZXF1aXJlKCdwZycpOwoKLy8gbm9tYnJlIEVYQUNUTyBlbiBlbCBjYXRhbG9nbyBkZSBjbHViZXMgKHZlciBsaXN0YXJfZnJh
bnF1aWNpYXMuanMpIC0+IGZlY2hhIHJlYWwgKElTTykuCmNvbnN0IEZFQ0hBU19SRUFMRVMgPSB7CiAgJ0NpdWRhZCBkZSBRdWVyZXRhcm8gKENpbWF0YXJp
byksIFFVRSc6ICcyMDIyLTAzLTE2JywKICAnUGxhemEgVG9ycmVjaWxsYXMsIFBVRSc6ICcyMDIyLTA0LTE0JywKICAnQ2l1ZGFkIGRlIFF1ZXJldGFybyAo
Q2FuZGlsZXMpLCBRUk8nOiAnMjAyMi0wNC0yMycsCiAgJ0N1ZXJuYXZhY2EgKEdhbGVyaWFzIEN1ZXJuYXZhY2EpLCBNT1InOiAnMjAyMi0wNC0yMycsCiAg
J0NpdWRhZCBkZSBNZXhpY28gKFBhc2VvIEFjb3hwYSksIENNWCc6ICcyMDIyLTA1LTMwJywKICAnUGxhemEgU2F0ZWxpdGUsIEVETyBNRVgnOiAnMjAyMi0w
Ni0wNicsCiAgJ0N1YXV0aXRsYW4gSXpjYWxsaSAoUGxhemEgU2FuIE1hcmNvcyksIE1FWCc6ICcyMDIyLTA0LTA3JywKICAnTGEgUGF6IFB1ZWJsYSwgUFVF
JzogJzIwMjItMTEtMTknLAogICdUbGFsbmVwYW50bGEgZGUgQmF6IChWYWxsZSBEb3JhZG8pLCBFRE8gTUVYJzogJzIwMjItMTItMTcnLAogICdFbmN1ZW50
cm8gT2NlYW5pYSwgQ0RNWCc6ICcyMDIzLTA5LTA5JywKICAnTGluZGF2aXN0YSwgTkwnOiAnMjAyMy0wNC0xMScsCiAgJ0xpYnJhbWllbnRvIChWaWxsYSBW
ZXJkZSksIFBVRSc6ICcyMDIzLTA0LTExJywKICAnUGFzZW8gVG9sbG9jYW4sIEVETyBNRVgnOiAnMjAyMy0xMS0xMScsCiAgJ1NhbnRhIENhdGFyaW5hLCBO
TCc6ICcyMDE4LTA0LTE0JywKICAnTW9udGVycmV5IChMYSBFc3Rhbnp1ZWxhKSwgTkwnOiAnMjAxOS0xMi0wOCcsCiAgJ0d1YWRhbHVwZSAoQXJjYWRpYSks
IE5MJzogJzIwMjAtMDEtMjUnLAogICdBcG9kYWNhIChFbCBNb2xpbm8pLCBOTCc6ICcyMDIwLTAxLTAyJywKICAnU2FsdGlsbG8gKFNhbnRhIElzYWJlbCks
IENPQSc6ICcyMDIwLTAxLTEwJywKICAnQW5nZWxvcG9saXMsIFBVRSc6ICcyMDI0LTAzLTMwJywKICAnQ29hY2FsY28sIEVETyBNRVgnOiAnMjAyNC0wMy0z
MCcsCiAgJ1B1bnRvIFJpbyBOaWxvLCBKQUwnOiAnMjAyNC0wMy0zMCcsCiAgJ0FjdWVkdWN0bywgQ0RNWCc6ICcyMDI0LTAzLTMwJywKICAnU2FuIEx1aXMg
UG90b3NpIChUaGUgUGFyayksIFNMUCc6ICcyMDI0LTA0LTEzJywKICAnWGFsYXBhIChQYXNlbyBKYXJkaW5lcyBYYWxhcGEpLCBWRVInOiAnMjAyNC0wNS0y
MScsCiAgJ0NlbnRlciBQbGF6YXMsIEVETyBNRVgnOiAnMjAyNC0xMS0wOScsCiAgJ1F1ZXJldGFybyAoQW50ZWEpLCBRUk8nOiAnMjAyNC0wOS0xMycsCiAg
J0NpdWRhZCBkZSBNZXhpY28gKE1peGNvYWMpLCBDRE1YJzogJzIwMjQtMTAtMTknLAogICdDdW1icmVzIGxhIFZpZ2EsIENETVgnOiAnMjAyNC0xMS0xNScs
CiAgJ0xhcyBBbWVyaWNhcyAoRWNhdGVwZWMpLCBFRE8gTUVYJzogJzIwMjQtMDctMTInLAogICdMZW9uLCBHVE8nOiAnMjAyNC0wNy0xMicsCiAgJ1ZlcmFj
cnV6IChMb3MgUGlub3MpLCBWRVInOiAnMjAyNC0xMi0yMScsCiAgJ0d1YWRhbGFqYXJhIChQbGF6YSBkZWwgQW5nZWwpLCBKQUwnOiAnMjAyNC0xMi0zMScs
CiAgJ01hemF0bGFuIChMYSBHcmFuIFBsYXphKSwgU0lOJzogJzIwMjUtMDUtMjQnLAogICdBbHRvbGl2bywgQ0RNWCc6ICcyMDI1LTEwLTE4JywKICAnVGxh
cXVlcGFxdWUgKENlbHRhKSwgSkFMJzogJzIwMjUtMTItMDYnLAogICdNZXJpZGEgKFBsYXphIEhhcmJvciksIFlVQyc6ICcyMDI1LTEyLTEzJywKICAnQ3Vs
aWFjYW4gKFBsYXphIEN1bGlhY2FuKSwgU0lOJzogJzIwMjUtMTItMjAnLAogICdHdWFkYWxhamFyYSAoUmFuY2hvIE51ZXZvKSAvIEVzdGFkaW8gR3VhZGFs
YWphcmEsIEpBTCc6ICcyMDI1LTEyLTIwJywKICAnTGVvbiAoUGFycXVlIFZlcnRpY2UpLCBHVE8nOiAnMjAyNS0xMi0yNycsCiAgJ01hbGVjb24gTGFzIEFt
ZXJpY2FzLCBST08nOiAnMjAyNS0xMi0yNycsCiAgJ1B1bnRvIFN1ciwgSkFMJzogJzIwMjUtMTItMjcnLAogICdHYWxlcmlhcyBHdWFkYWxhamFyYSwgSkFM
JzogJzIwMjUtMTItMjcnLAogICdNdWx0aXBsYXphIExhcyBQYWxtYXMsIEdSTyc6ICcyMDI1LTEyLTI3JywKICAnR3JhbnN1ciwgQ0RNWCc6ICcyMDI1LTEy
LTI3JywKICAnTWVyaWRhIChZdWNhbHBldGVuIC8gQ2FuZWspLCBZVUMnOiAnMjAyNi0wOC0zMScsCiAgJ0NlbnRybyBTYW50YSBGZSwgQ0RNWCc6ICcyMDI2
LTA5LTExJywKfTsKCmFzeW5jIGZ1bmN0aW9uIG1haW4oKSB7CiAgY29uc3QgY2xpZW50ID0gbmV3IENsaWVudCh7IGNvbm5lY3Rpb25TdHJpbmc6IHByb2Nl
c3MuZW52LkRBVEFCQVNFX1VSTCB9KTsKICBhd2FpdCBjbGllbnQuY29ubmVjdCgpOwogIGNvbnNvbGUubG9nKGBBcGxpY2FuZG8gZmVjaGFzIHJlYWxlcyBk
ZWwgZGlyZWN0b3JpbyBjb250cmEgJHtwcm9jZXNzLmVudi5EQVRBQkFTRV9VUkw/LnJlcGxhY2UoLzpbXjpAXStALywgJzoqKipAJyl9IC4uLlxuYCk7Cgog
IHRyeSB7CiAgICBsZXQgYWN0dWFsaXphZG9zID0gMDsKICAgIGNvbnN0IG5vRW5jb250cmFkb3MgPSBbXTsKICAgIGZvciAoY29uc3QgW25vbWJyZSwgZmVj
aGFdIG9mIE9iamVjdC5lbnRyaWVzKEZFQ0hBU19SRUFMRVMpKSB7CiAgICAgIGNvbnN0IHsgcm93cyB9ID0gYXdhaXQgY2xpZW50LnF1ZXJ5KAogICAgICAg
IGBVUERBVEUgY29udHJhdG9fZnJhbnF1aWNpYV9kZXRhbGxlcyBmZAogICAgICAgICBTRVQgY2x1Yl9hYmllcnRvID0gdHJ1ZSwgZmVjaGFfYXBlcnR1cmEg
PSAkMiwgdXBkYXRlZF9hdCA9IG5vdygpCiAgICAgICAgIEZST00gY2x1YmVzIGNsCiAgICAgICAgIFdIRVJFIGZkLmNsdWJfaWQgPSBjbC5pZCBBTkQgY2wu
bm9tYnJlID0gJDEKICAgICAgICAgUkVUVVJOSU5HIGNsLm5vbWJyZWAsCiAgICAgICAgW25vbWJyZSwgZmVjaGFdCiAgICAgICk7CiAgICAgIGlmIChyb3dz
Lmxlbmd0aCkgewogICAgICAgIGFjdHVhbGl6YWRvcyArPSAxOwogICAgICB9IGVsc2UgewogICAgICAgIG5vRW5jb250cmFkb3MucHVzaChub21icmUpOwog
ICAgICB9CiAgICB9CiAgICBjb25zb2xlLmxvZyhgQWN0dWFsaXphZG9zIGNvbiBmZWNoYSByZWFsOiAke2FjdHVhbGl6YWRvc30gZGUgJHtPYmplY3Qua2V5
cyhGRUNIQVNfUkVBTEVTKS5sZW5ndGh9IGVzcGVyYWRvcy5gKTsKICAgIGlmIChub0VuY29udHJhZG9zLmxlbmd0aCkgewogICAgICBjb25zb2xlLndhcm4o
J05vIHNlIGVuY29udHJhcm9uIChyZXZpc2FyIG5vbWJyZSBleGFjdG8gZW4gZWwgY2F0YWxvZ28gZGUgY2x1YmVzKTonKTsKICAgICAgZm9yIChjb25zdCBu
IG9mIG5vRW5jb250cmFkb3MpIGNvbnNvbGUud2FybihgICAtICR7bn1gKTsKICAgIH0KCiAgICAvLyBBdmlzbyBpbmZvcm1hdGl2bzogY3VhbGVzIGNsdWJl
cyBkZWwgc2lzdGVtYSBzZSBxdWVkYXJvbiBzaW4gdG9jYXIgKG5vIGVzdGFuIGVuIGVsIG1hcGEKICAgIC8vIGRlIGFycmliYSksIHBhcmEgcXVlIEphaXIg
c2VwYSBjdWFsZXMgc2lndWVuIGNvbiBmZWNoYSB0ZW50YXRpdmEgbyBzaW4gZmVjaGEuCiAgICBjb25zdCB7IHJvd3M6IHNpbkFjdHVhbGl6YXIgfSA9IGF3
YWl0IGNsaWVudC5xdWVyeSgKICAgICAgYFNFTEVDVCBjbC5ub21icmUsIGZkLmNsdWJfYWJpZXJ0bywgZmQuZmVjaGFfYXBlcnR1cmEKICAgICAgIEZST00g
Y29udHJhdG9fZnJhbnF1aWNpYV9kZXRhbGxlcyBmZAogICAgICAgSk9JTiBjbHViZXMgY2wgT04gY2wuaWQgPSBmZC5jbHViX2lkCiAgICAgICBXSEVSRSBj
bC5ub21icmUgIT0gQUxMKCQxOjp0ZXh0W10pCiAgICAgICBPUkRFUiBCWSBjbC5ub21icmVgLAogICAgICBbT2JqZWN0LmtleXMoRkVDSEFTX1JFQUxFUyld
CiAgICApOwogICAgY29uc29sZS5sb2coYFxuQ2x1YmVzIGRlbCBzaXN0ZW1hIHF1ZSBOTyBlc3RhbiBlbiBlbCBkaXJlY3RvcmlvIChzaW4gdG9jYXIgZW4g
ZXN0YSBjb3JyaWRhKTogJHtzaW5BY3R1YWxpemFyLmxlbmd0aH1gKTsKICAgIGZvciAoY29uc3QgciBvZiBzaW5BY3R1YWxpemFyKSB7CiAgICAgIGNvbnNv
bGUubG9nKGAgIC0gJHtyLm5vbWJyZX0gfCBhYmllcnRvPSR7ci5jbHViX2FiaWVydG99IHwgZmVjaGFfYXBlcnR1cmE9JHtyLmZlY2hhX2FwZXJ0dXJhID8/
ICdudWxsJ31gKTsKICAgIH0KICB9IGNhdGNoIChlcnIpIHsKICAgIGNvbnNvbGUuZXJyb3IoJ0Vycm9yIGFsIGFwbGljYXIgZmVjaGFzIHJlYWxlcyBkZWwg
ZGlyZWN0b3JpbzonLCBlcnIubWVzc2FnZSk7CiAgICBwcm9jZXNzLmV4aXRDb2RlID0gMTsKICB9IGZpbmFsbHkgewogICAgYXdhaXQgY2xpZW50LmVuZCgp
OwogIH0KfQoKbWFpbigpOwo=
"@
Write-FileFromBase64 -RelativePath "backend/prisma/marcar_fechas_reales_directorio.js" -Base64Content $b64

Write-Host ""
Write-Host "Listo. Archivos escritos. Siguiente paso:"
Write-Host "  git add -A"
Write-Host "  git commit -m 'Usar fechas reales de apertura del directorio de clubes'"
Write-Host "  git push"
Write-Host ""
Write-Host "Despues, desde backend/ con la DATABASE_URL de produccion en un .env local:"
Write-Host "  npm run fix:franquicias-fechas-directorio"