# ============================================================================
# Script de entrega: crear los 4 contratos de franquicia que faltaban
# (Tlatelolco, Andamar, Glorieta, Cuatro Caminos)
# ============================================================================
# El directorio publico marca estos 4 clubes como ya abiertos, pero no tenian
# contrato de franquicia en la plataforma. Se crean con datos BASICOS/PLACEHOLDER
# (club, fecha real de apertura, estatus activo) para que el dashboard cuadre
# con el directorio (50 abiertas). Falta completar el expediente real de cada
# uno (contraparte, terminos financieros, documento firmado) mas adelante.
#
# Como usarlo:
#   1) Corre este script desde la raiz del repo (fpt-contratos) en PowerShell.
#   2) git add -A ; git commit -m "..." ; git push
#   3) Con la DATABASE_URL de produccion en un .env local dentro de backend/:
#        npm run crear:franquicias-faltantes
#      Revisa en la consola que haya creado los 4 (folio nuevo para cada uno).
#      Borra el .env al terminar.
# ============================================================================

function Write-FileFromBase64 {
    param(
        [string]$RelativePath,
        [string]$Base64Content
    )
    $fullPath = Join-Path (Get-Location) $RelativePath
    $dir = Split-Path $fullPath -Parent
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    $bytes = [System.Convert]::FromBase64String($Base64Content)
    [System.IO.File]::WriteAllBytes($fullPath, $bytes)
    Write-Host "Escrito: $RelativePath"
}

Write-Host "Agregando creacion de contratos de franquicia faltantes..."

$b64 = @"
ewogICJuYW1lIjogImZwdC1jb250cmF0b3MtYmFja2VuZCIsCiAgInZlcnNpb24iOiAiMC4xLjAiLAogICJwcml2YXRlIjogdHJ1ZSwKICAiZGVzY3JpcHRp
b24iOiAiQmFja2VuZCBkZSBsYSBwbGF0YWZvcm1hIGRlIGdlc3Rpw7NuIGNvbnRyYWN0dWFsIChDTE0pIGRlIEZpdG5lc3MgUGFyYSBUb2RvcyAoRlBUKSIs
CiAgIm1haW4iOiAic3JjL3NlcnZlci5qcyIsCiAgInNjcmlwdHMiOiB7CiAgICAic3RhcnQiOiAibm9kZSBzcmMvc2VydmVyLmpzIiwKICAgICJkZXYiOiAi
bm9kZSAtLXdhdGNoIHNyYy9zZXJ2ZXIuanMiLAogICAgInNlZWQiOiAibm9kZSBwcmlzbWEvc2VlZC5qcyIsCiAgICAibWlncmF0ZTphcnJlbmRhbWllbnRv
cyI6ICJub2RlIHByaXNtYS9taWdyYXRlX2FycmVuZGFtaWVudG9zLmpzIiwKICAgICJtaWdyYXRlOmZyYW5xdWljaWEtYWxlcnRhcyI6ICJub2RlIHByaXNt
YS9taWdyYXRlX2ZyYW5xdWljaWFfYWxlcnRhcy5qcyIsCiAgICAiZml4OmZyYW5xdWljaWFzLWZpcm1hZG8iOiAibm9kZSBwcmlzbWEvbWFyY2FyX2ZyYW5x
dWljaWFzX2Zpcm1hZGFzLmpzIiwKICAgICJtaWdyYXRlOmZyYW5xdWljaWEtY2x1Yi1hYmllcnRvIjogIm5vZGUgcHJpc21hL21pZ3JhdGVfZnJhbnF1aWNp
YV9jbHViX2FiaWVydG8uanMiLAogICAgImZpeDpmcmFucXVpY2lhcy1jbHViLWFiaWVydG8iOiAibm9kZSBwcmlzbWEvbWFyY2FyX2NsdWJlc19ub19hYmll
cnRvcy5qcyIsCiAgICAiZml4OmZyYW5xdWljaWFzLWVuLWNvbnN0cnVjY2lvbiI6ICJub2RlIHByaXNtYS9tYXJjYXJfY2x1YmVzX2VuX2NvbnN0cnVjY2lv
bi5qcyIsCiAgICAibGlzdGFyOmZyYW5xdWljaWFzIjogIm5vZGUgcHJpc21hL2xpc3Rhcl9mcmFucXVpY2lhcy5qcyIsCiAgICAiZml4OmZyYW5xdWljaWFz
LWZlY2hhcy1mdXR1cmFzIjogIm5vZGUgcHJpc21hL2NvcnJlZ2lyX2ZlY2hhc19mdXR1cmFzLmpzIiwKICAgICJmaXg6ZnJhbnF1aWNpYXMtYXBlcnR1cmFz
LWNvbmZpcm1hZGFzIjogIm5vZGUgcHJpc21hL21hcmNhcl9hcGVydHVyYXNfY29uZmlybWFkYXMuanMiLAogICAgImZpeDpmcmFucXVpY2lhcy1mZWNoYXMt
ZGlyZWN0b3JpbyI6ICJub2RlIHByaXNtYS9tYXJjYXJfZmVjaGFzX3JlYWxlc19kaXJlY3RvcmlvLmpzIiwKICAgICJjcmVhcjpmcmFucXVpY2lhcy1mYWx0
YW50ZXMiOiAibm9kZSBwcmlzbWEvY3JlYXJfY29udHJhdG9zX2ZhbHRhbnRlcy5qcyIKICB9LAogICJkZXBlbmRlbmNpZXMiOiB7CiAgICAiYmNyeXB0Ijog
Il42LjAuMCIsCiAgICAiY29ycyI6ICJeMi44LjUiLAogICAgImRvY3h0ZW1wbGF0ZXIiOiAiXjMuNjkuMyIsCiAgICAiZG90ZW52IjogIl4xNi40LjUiLAog
ICAgImV4cHJlc3MiOiAiXjQuMTkuMiIsCiAgICAiZXhwcmVzcy1hc3luYy1lcnJvcnMiOiAiXjMuMS4xIiwKICAgICJqc29ud2VidG9rZW4iOiAiXjkuMC4y
IiwKICAgICJtdWx0ZXIiOiAiXjEuNC41LWx0cy4xIiwKICAgICJub2RlLWNyb24iOiAiXjMuMC4zIiwKICAgICJwZyI6ICJeOC4xMi4wIiwKICAgICJwaXp6
aXAiOiAiXjMuMi4wIgogIH0KfQo=
"@
Write-FileFromBase64 -RelativePath "backend/package.json" -Base64Content $b64

$b64 = @"
Ly8gRGEgZGUgYWx0YSA0IGNvbnRyYXRvcyBkZSBmcmFucXVpY2lhIHF1ZSBmYWx0YWJhbiBlbiBsYSBwbGF0YWZvcm1hLCBhdW5xdWUgbG9zIGNsdWJlcyB5
YQovLyBlc3RhbiBhYmllcnRvcyBzZWd1biBodHRwczovL2RpcmVjdG9yaW8uZnB0LmNvbS5teC8gKGZ1ZW50ZSBvZmljaWFsIGRlIE9wZXJhY2lvbmVzKToK
Ly8gICAtIFRsYXRlbG9sY28sIEFuZGFtYXIgeSBHbG9yaWV0YTogc29uIDMgZGUgbG9zIDQgY2x1YmVzIHF1ZSBxdWVkYXJvbiBwZW5kaWVudGVzIGRlCi8v
ICAgICB2YWxpZGFjaW9uIGNvbiBKdXJpZGljbyAoc2UgbGVzIG1hbmRvIGNvcnJlbyBkZSB2YWxpZGFjaW9uKS4gSmFpciBkZWNpZGlvICgyMDI2LTEwLTAz
KQovLyAgICAgZGFybG9zIGRlIGFsdGEgeWEgbWlzbW8gY29uIGRhdG9zIGJhc2ljb3MsIHBhcmEgcXVlIGVsIGRhc2hib2FyZCBjdWFkcmUgY29uIGVsCi8v
ICAgICBkaXJlY3RvcmlvLCBlbiB2ZXogZGUgZXNwZXJhciBhIHF1ZSBKdXJpZGljbyB0ZXJtaW5lIGRlIHZhbGlkYXIuCi8vICAgLSBDdWF0cm8gQ2FtaW5v
czogY2x1YiBudWV2byAoYWJyaW8gMjgtbWF5LTIwMjYpIGN1eW8gY29udHJhdG8gbnVuY2Egc2UgY3Jlby4KLy8KLy8gSU1QT1JUQU5URTogZXN0byBjcmVh
IHVuIGNvbnRyYXRvIGNvbiBkYXRvcyBNSU5JTU9TL1BMQUNFSE9MREVSIChjb250cmFwYXJ0ZSBnZW5lcmljYSwKLy8gc2luIG1vbnRvLCBzaW4gZG9jdW1l
bnRvcykuIFNpcnZlIHBhcmEgcXVlIGVsIGNsdWIgY3VlbnRlIGNvcnJlY3RhbWVudGUgZW4gZWwgZGFzaGJvYXJkIGRlCi8vIEZyYW5xdWljaWFzLCBwZXJv
IGVsIGV4cGVkaWVudGUgc2lndWUgaW5jb21wbGV0byAtLSBoYXkgcXVlIGVudHJhciBhIGNhZGEgdW5vIGRlc2RlCi8vIENvbnRyYXRvcy9GcmFucXVpY2lh
cyB5IGNvbXBsZXRhciBjb250cmFwYXJ0ZSByZWFsLCB0w6lybWlub3MgZmluYW5jaWVyb3MsIGRvY3VtZW50byBmaXJtYWRvLAovLyBldGMuIGN1YW5kbyBK
dXJpZGljbyB0ZXJtaW5lIGRlIHZhbGlkYXJsb3MuCi8vCi8vIFNlZ3VybyBkZSBjb3JyZXIgbWFzIGRlIHVuYSB2ZXo6IHNpIGVsIGNvbnRyYXRvIHlhIGV4
aXN0ZSAobWlzbW8gY2x1YiBjb24gdGlwbyBmcmFucXVpY2lhKSwKLy8gbm8gbG8gZHVwbGljYS4KLy8KLy8gRWplY3V0YXIgY29uOgovLyAgIG5vZGUgcHJp
c21hL2NyZWFyX2NvbnRyYXRvc19mYWx0YW50ZXMuanMKCnJlcXVpcmUoJ2RvdGVudicpLmNvbmZpZygpOwpjb25zdCB7IENsaWVudCB9ID0gcmVxdWlyZSgn
cGcnKTsKCi8vIG5vbWJyZSBhIHVzYXIgZW4gZWwgY2F0YWxvZ28gZGUgY2x1YmVzIChzZSBjcmVhIHNpIG5vIGV4aXN0ZSkgLT4gZGF0b3MgZGVsIGNvbnRy
YXRvLgpjb25zdCBDTFVCRVNfRkFMVEFOVEVTID0gWwogIHsgbm9tYnJlOiAnVGxhdGVsb2xjbywgQ0RNWCcsIGZlY2hhQXBlcnR1cmE6ICcyMDIzLTAyLTA5
JyB9LAogIHsgbm9tYnJlOiAnQW5kYW1hciwgVkVSJywgZmVjaGFBcGVydHVyYTogJzIwMjQtMTItMjEnIH0sCiAgeyBub21icmU6ICdHbG9yaWV0YSwgU0xQ
JywgZmVjaGFBcGVydHVyYTogJzIwMjQtMTItMzEnIH0sCiAgeyBub21icmU6ICdDdWF0cm8gQ2FtaW5vcywgRURPIE1FWCcsIGZlY2hhQXBlcnR1cmE6ICcy
MDI2LTA1LTI4JyB9LApdOwoKY29uc3QgUEFSVEVfRlBUID0gJ0ZpdG5lc3MgcGFyYSB0b2RvcywgUy4gZGUgUi5MLiBkZSBDLlYuJzsKCmFzeW5jIGZ1bmN0
aW9uIGdlbmVyYXJGb2xpbyhjbGllbnQsIGFuaW8gPSBuZXcgRGF0ZSgpLmdldEZ1bGxZZWFyKCkpIHsKICBhd2FpdCBjbGllbnQucXVlcnkoJ1NFTEVDVCBw
Z19hZHZpc29yeV94YWN0X2xvY2soaGFzaHRleHQoJDEpKScsIFtgZm9saW8tY29udHJhdG8tJHthbmlvfWBdKTsKICBjb25zdCBwcmVmaWpvID0gYENULSR7
YW5pb30tYDsKICBjb25zdCB7IHJvd3MgfSA9IGF3YWl0IGNsaWVudC5xdWVyeSgKICAgIGBTRUxFQ1QgZm9saW8gRlJPTSBjb250cmF0b3MgV0hFUkUgZm9s
aW8gTElLRSAkMSBPUkRFUiBCWSBmb2xpbyBERVNDIExJTUlUIDFgLAogICAgW2Ake3ByZWZpam99JWBdCiAgKTsKICBsZXQgc2lndWllbnRlID0gMTsKICBp
ZiAocm93cy5sZW5ndGggPiAwKSB7CiAgICBjb25zdCBudW1lcm8gPSBwYXJzZUludChyb3dzWzBdLmZvbGlvLnNsaWNlKHByZWZpam8ubGVuZ3RoKSwgMTAp
OwogICAgaWYgKCFOdW1iZXIuaXNOYU4obnVtZXJvKSkgc2lndWllbnRlID0gbnVtZXJvICsgMTsKICB9CiAgcmV0dXJuIGAke3ByZWZpam99JHtTdHJpbmco
c2lndWllbnRlKS5wYWRTdGFydCg0LCAnMCcpfWA7Cn0KCmFzeW5jIGZ1bmN0aW9uIG1haW4oKSB7CiAgY29uc3QgY2xpZW50ID0gbmV3IENsaWVudCh7IGNv
bm5lY3Rpb25TdHJpbmc6IHByb2Nlc3MuZW52LkRBVEFCQVNFX1VSTCB9KTsKICBhd2FpdCBjbGllbnQuY29ubmVjdCgpOwogIGNvbnNvbGUubG9nKGBDcmVh
bmRvIGNvbnRyYXRvcyBmYWx0YW50ZXMgY29udHJhICR7cHJvY2Vzcy5lbnYuREFUQUJBU0VfVVJMPy5yZXBsYWNlKC86W146QF0rQC8sICc6KioqQCcpfSAu
Li5cbmApOwoKICB0cnkgewogICAgY29uc3QgeyByb3dzOiB0aXBvUm93cyB9ID0gYXdhaXQgY2xpZW50LnF1ZXJ5KAogICAgICBgU0VMRUNUIGlkIEZST00g
dGlwb3NfY29udHJhdG8gV0hFUkUgZXNfZnJhbnF1aWNpYSA9IHRydWUgTElNSVQgMWAKICAgICk7CiAgICBpZiAoIXRpcG9Sb3dzLmxlbmd0aCkgdGhyb3cg
bmV3IEVycm9yKCdObyBzZSBlbmNvbnRybyB1biB0aXBvX2NvbnRyYXRvIGNvbiBlc19mcmFucXVpY2lhID0gdHJ1ZS4nKTsKICAgIGNvbnN0IHRpcG9Db250
cmF0b0lkID0gdGlwb1Jvd3NbMF0uaWQ7CgogICAgY29uc3QgeyByb3dzOiB1c2VyUm93cyB9ID0gYXdhaXQgY2xpZW50LnF1ZXJ5KAogICAgICBgU0VMRUNU
IGlkIEZST00gdXN1YXJpb3MgV0hFUkUgZW1haWwgPSAnamFpckBmcHQuY29tLm14JyBMSU1JVCAxYAogICAgKTsKICAgIGlmICghdXNlclJvd3MubGVuZ3Ro
KSB0aHJvdyBuZXcgRXJyb3IoJ05vIHNlIGVuY29udHJvIGVsIHVzdWFyaW8gamFpckBmcHQuY29tLm14IHBhcmEgYXNpZ25hciBjb21vIHNvbGljaXRhbnRl
LicpOwogICAgY29uc3Qgc29saWNpdGFkb1BvcklkID0gdXNlclJvd3NbMF0uaWQ7CgogICAgZm9yIChjb25zdCB7IG5vbWJyZSwgZmVjaGFBcGVydHVyYSB9
IG9mIENMVUJFU19GQUxUQU5URVMpIHsKICAgICAgYXdhaXQgY2xpZW50LnF1ZXJ5KCdCRUdJTicpOwogICAgICB0cnkgewogICAgICAgIC8vIDEpIENsdWI6
IHVzYXIgZWwgZXhpc3RlbnRlIHNpIHlhIGVzdGEgZW4gZWwgY2F0YWxvZ28sIG8gY3JlYXJsby4KICAgICAgICBsZXQgeyByb3dzOiBjbHViUm93cyB9ID0g
YXdhaXQgY2xpZW50LnF1ZXJ5KCdTRUxFQ1QgaWQgRlJPTSBjbHViZXMgV0hFUkUgbm9tYnJlID0gJDEnLCBbbm9tYnJlXSk7CiAgICAgICAgbGV0IGNsdWJJ
ZDsKICAgICAgICBpZiAoY2x1YlJvd3MubGVuZ3RoKSB7CiAgICAgICAgICBjbHViSWQgPSBjbHViUm93c1swXS5pZDsKICAgICAgICB9IGVsc2UgewogICAg
ICAgICAgY29uc3QgeyByb3dzOiBudWV2b0NsdWIgfSA9IGF3YWl0IGNsaWVudC5xdWVyeSgKICAgICAgICAgICAgJ0lOU0VSVCBJTlRPIGNsdWJlcyAobm9t
YnJlKSBWQUxVRVMgKCQxKSBSRVRVUk5JTkcgaWQnLAogICAgICAgICAgICBbbm9tYnJlXQogICAgICAgICAgKTsKICAgICAgICAgIGNsdWJJZCA9IG51ZXZv
Q2x1YlswXS5pZDsKICAgICAgICAgIGNvbnNvbGUubG9nKGBDbHViIGNyZWFkbyBlbiBlbCBjYXRhbG9nbzogJHtub21icmV9YCk7CiAgICAgICAgfQoKICAg
ICAgICAvLyAyKSBTaSB5YSBleGlzdGUgdW4gY29udHJhdG8gZGUgZnJhbnF1aWNpYSBwYXJhIGVzdGUgY2x1Yiwgbm8gZHVwbGljYXIuCiAgICAgICAgY29u
c3QgeyByb3dzOiBleGlzdGVudGUgfSA9IGF3YWl0IGNsaWVudC5xdWVyeSgKICAgICAgICAgIGBTRUxFQ1QgYy5mb2xpbyBGUk9NIGNvbnRyYXRvcyBjCiAg
ICAgICAgICAgSk9JTiBjb250cmF0b19mcmFucXVpY2lhX2RldGFsbGVzIGZkIE9OIGZkLmNvbnRyYXRvX2lkID0gYy5pZAogICAgICAgICAgIFdIRVJFIGZk
LmNsdWJfaWQgPSAkMWAsCiAgICAgICAgICBbY2x1YklkXQogICAgICAgICk7CiAgICAgICAgaWYgKGV4aXN0ZW50ZS5sZW5ndGgpIHsKICAgICAgICAgIGNv
bnNvbGUubG9nKGBZYSBleGlzdGUgY29udHJhdG8gcGFyYSAke25vbWJyZX0gKCR7ZXhpc3RlbnRlWzBdLmZvbGlvfSksIG5vIHNlIGR1cGxpY2EuYCk7CiAg
ICAgICAgICBhd2FpdCBjbGllbnQucXVlcnkoJ1JPTExCQUNLJyk7CiAgICAgICAgICBjb250aW51ZTsKICAgICAgICB9CgogICAgICAgIC8vIDMpIENyZWFy
IGVsIGNvbnRyYXRvIChwbGFjZWhvbGRlciwgZXN0YXR1cyBhY3Rpdm8gLS0gaWd1YWwgcXVlIGVsIHJlc3RvIGRlCiAgICAgICAgLy8gICAgZnJhbnF1aWNp
YXMsIHF1ZSBubyBwYXNhbiBwb3IgZmx1am8gZGUgYXV0b3JpemFjaW9uKS4KICAgICAgICBjb25zdCBmb2xpbyA9IGF3YWl0IGdlbmVyYXJGb2xpbyhjbGll
bnQpOwogICAgICAgIGNvbnN0IHsgcm93czogY29udHJhdG9Sb3dzIH0gPSBhd2FpdCBjbGllbnQucXVlcnkoCiAgICAgICAgICBgSU5TRVJUIElOVE8gY29u
dHJhdG9zCiAgICAgICAgICAgICAoZm9saW8sIHRpdHVsbywgZGVzY3JpcGNpb24sIHRpcG9fY29udHJhdG9faWQsIHBhcnRlLCBjb250cmFwYXJ0ZV9ub21i
cmUsCiAgICAgICAgICAgICAgZmVjaGFfaW5pY2lvLCBlc3RhdHVzLCBzb2xpY2l0YWRvX3Bvcl9pZCkKICAgICAgICAgICBWQUxVRVMgKCQxLCQyLCQzLCQ0
LCQ1LCQ2LCQ3LCdhY3Rpdm8nLCQ4KQogICAgICAgICAgIFJFVFVSTklORyBpZCwgZm9saW9gLAogICAgICAgICAgWwogICAgICAgICAgICBmb2xpbywKICAg
ICAgICAgICAgYENvbnRyYXRvIGRlIEZyYW5xdWljaWEgLSAke25vbWJyZX1gLAogICAgICAgICAgICAnQWx0YSBjb24gZGF0b3MgYmFzaWNvcyAoY2x1YiB5
YSBhYmllcnRvIHNlZ3VuIGRpcmVjdG9yaW8uZnB0LmNvbS5teCk7IGV4cGVkaWVudGUgJyArCiAgICAgICAgICAgICAgJ3BlbmRpZW50ZSBkZSBjb21wbGV0
YXI6IGNvbnRyYXBhcnRlIHJlYWwsIHRlcm1pbm9zIGZpbmFuY2llcm9zIHkgZG9jdW1lbnRvIGZpcm1hZG8uJywKICAgICAgICAgICAgdGlwb0NvbnRyYXRv
SWQsCiAgICAgICAgICAgIFBBUlRFX0ZQVCwKICAgICAgICAgICAgYEZyYW5xdWljaWF0YXJpbyBkZSAke25vbWJyZX0gKHBlbmRpZW50ZSBkZSBjb21wbGV0
YXIgZXhwZWRpZW50ZSlgLAogICAgICAgICAgICBmZWNoYUFwZXJ0dXJhLAogICAgICAgICAgICBzb2xpY2l0YWRvUG9ySWQsCiAgICAgICAgICBdCiAgICAg
ICAgKTsKICAgICAgICBjb25zdCBjb250cmF0byA9IGNvbnRyYXRvUm93c1swXTsKCiAgICAgICAgLy8gNCkgRGF0b3MgZGUgZnJhbnF1aWNpYTogY2x1Yiwg
eWEgYWJpZXJ0bywgY29uIHN1IGZlY2hhIHJlYWwuCiAgICAgICAgYXdhaXQgY2xpZW50LnF1ZXJ5KAogICAgICAgICAgYElOU0VSVCBJTlRPIGNvbnRyYXRv
X2ZyYW5xdWljaWFfZGV0YWxsZXMgKGNvbnRyYXRvX2lkLCBjbHViX2lkLCBjbHViX2FiaWVydG8sIGZlY2hhX2FwZXJ0dXJhKQogICAgICAgICAgIFZBTFVF
UyAoJDEsJDIsdHJ1ZSwkMylgLAogICAgICAgICAgW2NvbnRyYXRvLmlkLCBjbHViSWQsIGZlY2hhQXBlcnR1cmFdCiAgICAgICAgKTsKCiAgICAgICAgYXdh
aXQgY2xpZW50LnF1ZXJ5KCdDT01NSVQnKTsKICAgICAgICBjb25zb2xlLmxvZyhgQ3JlYWRvOiAke2NvbnRyYXRvLmZvbGlvfSAtICR7bm9tYnJlfSAoYXBl
cnR1cmEgJHtmZWNoYUFwZXJ0dXJhfSlgKTsKICAgICAgfSBjYXRjaCAoZXJyKSB7CiAgICAgICAgYXdhaXQgY2xpZW50LnF1ZXJ5KCdST0xMQkFDSycpOwog
ICAgICAgIGNvbnNvbGUuZXJyb3IoYEVycm9yIGFsIGNyZWFyIGNvbnRyYXRvIHBhcmEgJHtub21icmV9OmAsIGVyci5tZXNzYWdlKTsKICAgICAgfQogICAg
fQogIH0gY2F0Y2ggKGVycikgewogICAgY29uc29sZS5lcnJvcignRXJyb3IgZ2VuZXJhbDonLCBlcnIubWVzc2FnZSk7CiAgICBwcm9jZXNzLmV4aXRDb2Rl
ID0gMTsKICB9IGZpbmFsbHkgewogICAgYXdhaXQgY2xpZW50LmVuZCgpOwogIH0KfQoKbWFpbigpOwo=
"@
Write-FileFromBase64 -RelativePath "backend/prisma/crear_contratos_faltantes.js" -Base64Content $b64

Write-Host ""
Write-Host "Listo. Archivos escritos. Siguiente paso:"
Write-Host "  git add -A"
Write-Host "  git commit -m 'Crear contratos de franquicia faltantes (Tlatelolco, Andamar, Glorieta, Cuatro Caminos)'"
Write-Host "  git push"
Write-Host ""
Write-Host "Despues, desde backend/ con la DATABASE_URL de produccion en un .env local:"
Write-Host "  npm run crear:franquicias-faltantes"